### ISSUE TITLE
Info - arm version iofogctl

### ISSUE THREAD

**Issue by Salvocll** [eclipse-iofog/iofogctl#42]
Hi,
Initially, being an Edge platform I thought it would work also with raspberry Pi with raspbian stretch (arm architecture), I tried to include the cli via the script:

```
curl -s https://packagecloud.io/install/repositories/iofog/iofogctl/script.deb.sh | sudo bash
```

the script seemed to have done its job but when installing the iofogctl package this was not found in the repository.

Then I thought it was an arm problem so I tested the same script on my host (linux mint tina) and got the same result.

Going deeper into the search for a possible solution, I found the repo:

[https://packagecloud.io/iofog/iofogctl](https://packagecloud.io/iofog/iofogctl)

and I noticed that there are no versions for arm .. but I noticed the strange dissonance of the package raspbian stretch with amd65.deb of the package associated with it.

note: Later I managed to manually install the package on my host, by manual installation:

[https://packagecloud.io/iofog/iofogctl/install#manual](https://packagecloud.io/iofog/iofogctl/install#manual)

**Comment by SergeRadinovich** [comment]
Hi Salvocll. We don't currently support ARM for iofogctl. Apologies that this is not clear in the README.

iofogctl is intended to deploy platform/apps to the edge (remotely). We have not focused on making it an application that runs on the edge itself.

Having said that, we will look into supporting ARM in the near future.

**Comment by SergeRadinovich** [comment]
@Salvocll could you please explain why apt install did not work on Mint in the first instance?

**Comment by Pixcell** [comment]
@Salvocll We will clarify what platform are supported by iofogctl.
But since you have managed to install iofogctl following the manual installation steps, we will close this issue.

Please feel free to reopen it, or open a new one if you were to encounter any issue using iofogctl or ioFog

Regards,
